version: '3'

services:
    # Database
    mysqldb:
        container_name: mysql-database
        image: mysql:5.7
        volumes:
            - mysqldb_data:/var/lib/mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: P@ssw0rd
            MYSQL_DATABASE: wpdatabase
            MYSQL_USER: wpadmin
            MYSQL_PASSWORD: P@ssw0rd
        networks:
            - wpnetwork
    # phpmyadmin
    phpmyadmin:
        container_name: phpmyadmin-portal
        depends_on:
            - mysqldb
        image: phpmyadmin/phpmyadmin
        restart: always
        ports:
            - '8080:80'
        environment:
            PMA_HOSTS: mysqldb
            MYSQL_ROOT_PASSWORD: P@ssw0rd
        networks:
            - wpnetwork
    # WordPress
    wordpress:
        container_name: wordpress-server
        depends_on:
            - mysqldb
        image: wordpress:latest
        ports:
            - '8000:80'
        restart: always
        volumes: ['./environment:/var/www/html']
        environment:
            WORDPRESS_DB_HOST: mysqldb:3306
            WORDPRESS_DB_NAME: wpdatabase
            WORDPRESS_DB_USER: wpadmin
            WORDPRESS_DB_PASSWORD: P@ssw0rd
        networks:
            - wpnetwork
networks:
    wpnetwork:
volumes:
    mysqldb_data: